# Generated by Django 4.0.2 on 2022-11-01 12:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('storeApp', '0002_alter_customuser_countoforders_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Cards',
            new_name='Card',
        ),
        migrations.RenameModel(
            old_name='Categories',
            new_name='Category',
        ),
        migrations.RenameModel(
            old_name='Feedbacks',
            new_name='Feedback',
        ),
        migrations.RenameModel(
            old_name='Images',
            new_name='Image',
        ),
        migrations.RenameModel(
            old_name='Orders',
            new_name='Order',
        ),
        migrations.RenameModel(
            old_name='Products',
            new_name='Product',
        ),
    ]
