# Generated by Django 4.0.2 on 2022-11-01 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storeApp', '0004_alter_product_discountprice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='discountPrice',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
